### ISSUE TITLE
Add synonym_property config to OLS

### ISSUE THREAD

**Issue by marius-mather** [monarch-initiative/vertebrate-breed-ontology#62]
For my use cases in OMIA/AHIDA, it would be very useful to get synonyms for breed names directly in the OLS API. They are available when looking up individual terms, but don't currently appear in search endpoints.

As far as I can tell, configuring synonyms correctly for OLS involves adding some configuration to https://github.com/EBISPOT/OLS-Config/blob/prod/ols-ontologies.yaml, the configuration would be something like:

```yaml
## VBO override
  - id: vbo
    synonym_property:
      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
```

I'm happy to put in a PR for this at https://github.com/EBISPOT/OLS-Config/, but let me know if this is the right way to go about it.
